### ISSUE TITLE
Please update fmtlib to recent versions

### ISSUE THREAD

**Issue by jspanchu** [diatomic/diy#93]
The version of `thirdparty/fmt` is old. Please bring it up to date because it currently uses the deprecated `char_traits` which has now been removed from LLVM's libc++ last year https://github.com/llvm/llvm-project/pull/72694.

Because of this, we are unable to update the compiler for VTK.wasm

https://open.cdash.org/viewBuildError.php?buildid=10174349

```
[ThirdParty/diy2/vtkdiy2/include/vtkdiy2/fmt/core.h:272](https://gitlab.kitware.com/vtk/vtk/blob/ad4a5650d180f480be86fc8c98fa509e8013ee44/ThirdParty/diy2/vtkdiy2/include/vtkdiy2/fmt/core.h#L272):30: error: implicit instantiation of undefined template 'std::char_traits<fmt::char8_t>'
  272 |       : data_(s), size_(std::char_traits<Char>::length(s)) {}
      |                              ^
[ThirdParty/diy2/vtkdiy2/include/vtkdiy2/fmt/format.h:487](https://gitlab.kitware.com/vtk/vtk/blob/ad4a5650d180f480be86fc8c98fa509e8013ee44/ThirdParty/diy2/vtkdiy2/include/vtkdiy2/fmt/format.h#L487):9: note: in instantiation of member function 'fmt::basic_string_view<fmt::char8_t>::basic_string_view' requested here
  487 |       : basic_string_view<char8_t>(reinterpret_cast<const char8_t*>(s)) {}
      |         ^
```

**Comment by MehdiChinoune** [comment]
see https://github.com/diatomic/diy/issues/92

**Comment by mrzv** [comment]
@jspanchu @vicentebolea Can you comment on this? Per @MehdiChinoune comment, this seems like the same issue with DIY being outdated in VTK. Can you update it, so this doesn't keep coming up?

**Comment by jspanchu** [comment]
I am right now working on updating VTK's copy of diy to 3.6.0 to test the theory that diy==3.6.0 solves my issue. Right now, there are some VTK classes which fail to compile, will look into fixing it.

```
C:\Users\jaswant.panchumarti\dev\vtk\Filters\ParallelDIY2\vtkPResampleToImage.cxx(340): error C2440: 'initializing': cannot convert from 'vtkdiy2::Master::Proxy::IncomingQueues' to 'vtkdiy2::Master::IncomingQueues &'
C:\Users\jaswant.panchumarti\dev\vtk\Filters\ParallelDIY2\vtkPResampleToImage.cxx(343): error C2451: a conditional expression of type '_Ty2' is not valid
        with
        [
            _Ty2=vtkdiy2::Master::RecordQueue
        ]
C:\Users\jaswant.panchumarti\dev\vtk\Filters\ParallelDIY2\vtkPResampleToImage.cxx(343): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

**Comment by jspanchu** [comment]
Not sure if it will work, but I replaced `vtkdiy2::Master::IncomingQueues` with `vtkdiy2::Master::Proxy::IncomingQueues` and it compiled. I see that the proxy type is actually totally different `std::map<int,     MemoryBuffer>` vs `concurrent_map<int,      RecordQueue>`

Just one more error now, should be fixable..

```
C:\Users\jaswant.panchumarti\dev\vtk\Filters\ParallelDIY2\vtkPResampleToImage.cxx(340): error C2440: 'initializing': cannot convert from 'vtkdiy2::Master::Proxy::IncomingQueues' to 'vtkdiy2::Master::IncomingQueues &'
C:\Users\jaswant.panchumarti\dev\vtk\Filters\ParallelDIY2\vtkPResampleToImage.cxx(343): error C2451: a conditional expression of type '_Ty2' is not valid
        with
        [
            _Ty2=vtkdiy2::Master::RecordQueue
        ]
C:\Users\jaswant.panchumarti\dev\vtk\Filters\ParallelDIY2\vtkPResampleToImage.cxx(343): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

**Comment by vicentebolea** [comment]
I see, thanks @jspanchu for point this out, update it in VTK and fix the build errors, let me know if you need help to bring the changes back to DIY.
